"""Streamlit Dashboard for Groww Reviews Weekly Pulse."""

import streamlit as st
import json
import sqlite3
from pathlib import Path
import sys

# Add paths
sys.path.insert(0, str(Path(__file__).parent / "phase2"))
sys.path.insert(0, str(Path(__file__).parent / "phase3"))

st.set_page_config(
    page_title="Groww Reviews Dashboard",
    page_icon="📊",
    layout="wide"
)

# Load data
@st.cache_data
def load_stats():
    db_path = Path(__file__).parent / "phase2" / "data" / "processed_reviews.db"
    if not db_path.exists():
        return None
    
    with sqlite3.connect(db_path) as conn:
        cursor = conn.execute("SELECT COUNT(*) FROM reviews")
        total = cursor.fetchone()[0]
        
        cursor = conn.execute("SELECT rating, COUNT(*) FROM reviews GROUP BY rating")
        rating_dist = dict(cursor.fetchall())
        
        cursor = conn.execute("SELECT MIN(review_date), MAX(review_date) FROM reviews")
        date_range = cursor.fetchone()
    
    return {
        "total": total,
        "rating_dist": rating_dist,
        "date_range": date_range
    }

@st.cache_data
def load_report():
    report_path = Path(__file__).parent / "phase3" / "outputs" / "weekly_pulse.json"
    if not report_path.exists():
        return None
    
    with open(report_path, 'r') as f:
        return json.load(f)

# Header
st.title("📊 Groww Reviews Dashboard")
st.markdown("Weekly Product Insight Summary")

# Load data
stats = load_stats()
report = load_report()

if not stats or not report:
    st.error("No data found. Please run the data collection and analysis first.")
    st.stop()

# Stats row
col1, col2, col3, col4 = st.columns(4)
with col1:
    st.metric("Total Reviews", stats['total'])
with col2:
    st.metric("1-Star Reviews", stats['rating_dist'].get(1, 0))
with col3:
    st.metric("2-Star Reviews", stats['rating_dist'].get(2, 0))
with col4:
    st.metric("Date Range", f"{stats['date_range'][0]} to {stats['date_range'][1]}" if stats['date_range'] else "N/A")

st.divider()

# Top Themes
st.subheader("🔥 Top 3 Themes")
themes = report.get('themes', [])[:3]
cols = st.columns(3)
icons = ['🔥', '⚡', '💡']
for i, (theme, col) in enumerate(zip(themes, cols)):
    with col:
        st.markdown(f"**{icons[i]} Theme {i+1}**")
        st.markdown(f"### {theme['name']}")
        st.markdown(f"{theme['review_count']} mentions")
        st.markdown(f"*{theme['description']}*")

st.divider()

# Three columns layout
col1, col2, col3 = st.columns(3)

# Themes column
with col1:
    st.subheader("☰ Top 3 Themes")
    for theme in themes:
        with st.container():
            st.markdown(f"**{theme['name']}**")
            st.markdown(f"{theme['description']}")
            st.markdown("---")

# Quotes column
with col2:
    st.subheader("❝ User Quotes")
    quotes = report.get('quotes', [])[:3]
    for quote in quotes:
        with st.container():
            st.markdown(f"> *\"{quote['text']}\"*")
            st.markdown(f"— {quote['theme']}")
            st.markdown("---")

# Actions column
with col3:
    st.subheader("⚡ Action Ideas")
    actions = report.get('actions', [])[:3]
    for i, action in enumerate(actions):
        with st.container():
            st.markdown(f"**{i+1}. {action['title']}**")
            st.markdown(f"{action['description']}")
            st.markdown(f"Priority: `{action['priority']}` | Effort: `{action['effort']}`")
            st.markdown("---")

# Email section
st.divider()
st.subheader("📧 Send Report via Email")

with st.form("email_form"):
    to_email = st.text_input("Recipient Email", placeholder="product-team@company.com")
    subject = st.text_input("Subject", value="Weekly Pulse - Groww Reviews")
    
    col1, col2 = st.columns([3, 1])
    with col2:
        submitted = st.form_submit_button("Send Email", use_container_width=True)
    
    if submitted:
        if to_email:
            try:
                sys.path.insert(0, str(Path(__file__).parent / "backend"))
                from app.core.config import get_settings
                from app.api.email import send_email_via_smtp, generate_email_content
                
                settings = get_settings()
                email_body = generate_email_content(report)
                
                send_email_via_smtp(
                    to_email=to_email,
                    subject=subject,
                    html_body=email_body,
                    settings=settings
                )
                st.success(f"✅ Email sent to {to_email}")
            except Exception as e:
                st.error(f"❌ Failed to send email: {str(e)}")
        else:
            st.warning("Please enter an email address")

# Footer
st.divider()
st.markdown("*Generated by GrowwReviews AI Tool*")
